# Generated by Django 3.2.5 on 2021-07-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.IntegerField(default=None),
        ),
    ]
