# Generated by Django 3.2.5 on 2021-07-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
