# Generated by Django 3.2.5 on 2021-07-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210722_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
